stages:
  - build
  - test


build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  artifacts:
    paths: 
      - build
  script:
      - git clone $CLONE_URL src
      - git -C src checkout $HEAD_SHA
      - >
        cmake -S src -B build -GNinja
        -DCMAKE_BUILD_TYPE=Release
        -DTRACCC_BUILD_TESTING=ON
        -DTRACCC_BUILD_CUDA=ON
      - cmake --build build


test_cuda:
  stage: test
  tags: [docker-gpu-nvidia]
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  needs: 
    - build_cuda
  script:
    - apt-get update && apt-get install -y git-lfs
    - git clone $CLONE_URL src
    - git -C src checkout $HEAD_SHA
    - git -C src submodule init && git -C src submodule update
    - cd build
    - nvidia-smi
    - ctest --output-on-failure

