name: Builds

on:
  push:
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  
jobs:
  builds:
    name: ${{ matrix.platform.name }}-${{ matrix.build }}
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/ubuntu2004:v11
    strategy:
      matrix:
        platform:
          - name: CPU
            container: ghcr.io/acts-project/ubuntu2004:v11
          - name: CUDA
            container: ghcr.io/acts-project/ubuntu1804_cuda:v11
        build:
          - Release
          - Debug
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} -B build -S .
      - name: Build
        run: cmake --build build -- -j$(nproc)
      - name: Run tests & examples
        run: CTEST_PARALLEL_LEVEL=$(nproc) cmake --build build -- test
          
